services:
  postgres-db:
    image: postgres:14
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=jokes_pg
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "jokes_pg", "-U", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - 80:80
    depends_on:
      postgres-db:
        condition: service_healthy
